---
version: 4.2.0
name: Knowledge of my life
#theme: jekyll-theme-cayman
description: Transform your plain text into static websites and blogs
url: https://github.com/toshio-dot-com/knowledgeofmylife
repository: https://github.com/toshio-dot-com/knowledgeofmylife
timezone: Asia/Tokyo
encording: utf-8
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
future: true
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
feed:
  categories:
  - release
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed
strict_front_matter: true
