---
version: 4.2.0
name: Knowledge of my life
theme: jekyll-theme-cayman
description: Transform your plain text into static websites and blogs
url: https://github.com/toshio-dot-com/knowledgeofmylife
repository: https://github.com/toshio-dot-com/knowledgeofmylife
#logo: "/img/logo-2x.png"
#google_analytics_id: UA-50755011-1
#google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
#cloudinary_url: https://res.cloudinary.com/jekyll/image/upload/f_auto,q_auto,w_404
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: business
    type: business
  values:
    layout: business
#- scope:
#    path: ''
#  values:
#    image: "/img/jekyll-og.png"
future: true
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
feed:
  categories:
  - release
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed
strict_front_matter: true
exclude:
- icomoon-selection.json
- readme.md
